### ISSUE TITLE
add library for windows connector to config file

### ISSUE THREAD

**Issue by kafisatz** [JuliaDB/MySQL.jl#12]
Here is the line which is needed to make things work on windows. 
I used the C connector from here: http://dev.mysql.com/downloads/connector/c/

@windows_only lib_choices=["C:\\Program Files\\MySQL\\MySQL Connector C 6.1\\lib\\libmysql.dll"]

**Comment by nkottary** [comment]
I have added `@windows_only lib_choices = ["libmysql.dll"]` to config.jl

You will need to add "C:\Program Files\MySQL\MySQL Connector C 6.1\lib\" to your PATH variable in the environment variables settings since this would be different for different users.

**Comment by kafisatz** [comment]
Thank you. This works like a charm. (libmysql.dll)
Although I am now using 
 libmariadb.dll 
and for this I again need to change the line... 
I don't know whether you intended that users use your package for MariaDBs. I do not even know the differences between the two.
For me your package works great with MariaDB though.
Thus if it were possible to have a user parameter to set the *.dll file that would be great.

**Comment by kafisatz** [comment]
Feel free to close this!

**Comment by nkottary** [comment]
I have added libmariadb.dll to lib_choices 0a6c47d
