### ISSUE TITLE
Error when requesting a Dataframe mysql_execute_query(con,command) 

### ISSUE THREAD

**Issue by kafisatz** [JuliaDB/MySQL.jl#14]
when I request a dataframe with a query like

    command = """SELECT * from market16m LIMIT 12;"""
    df=mysql_execute_query(con,command);

I get an error during df construction.

by adding and Int64() in results.jl line 266 this seems to be fixed in my case:

    df = DataFrame(jfield_types, field_headers, Int64(nrows))

**Comment by nkottary** [comment]
Can you paste the error message here ?

**Comment by kafisatz** [comment]
julia>

julia> command = """SELECT * from market16m LIMIT 12;""" #
"SELECT * from market16m LIMIT 12;"

julia> @time x=mysql_execute_query(con,command,MYSQL_ARRAY);
  0.004890 seconds (2.61 k allocations: 117.438 KB)

julia> @time xdf=mysql_execute_query(con,command);
ERROR: MethodError: `convert` has no method matching convert(::Type{BitArray{N}}
, ::Int32)
This may have arisen from a call to the constructor BitArray{N}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T,N}(::Type{BitArray{N}}, ::AbstractArray{T,N})
  convert{T}(::Type{T}, ::T)
  ...
 in call at essentials.jl:56
 in call at C:\Users\workstation\.julia\DataFrames\src\dataframe\dataframe.jl:13
0
 in mysql_result_to_dataframe at C:\Users\workstation\.julia\MySQL\src\results.j
l:266
 in mysql_execute_query at C:\Users\workstation\.julia\MySQL\src\handy.jl:73
 in mysql_execute_query at C:\Users\workstation\.julia\MySQL\src\handy.jl:59

julia>

julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia>

**Comment by nkottary** [comment]
I have pushed a fix for this now.

This is because of the way BitArray is defined in julia base. It doesnt have a constructor for 32 bit integer.

I think you are using a 32-bit mysql connector, because of which the mysql_num_rows() is returning a 32-bit int instead of 64-bit,

**Comment by kafisatz** [comment]
Thanks. I will take a look at my connector. The fix works for me.
