### ISSUE TITLE
BIGINT leads to overflow error

### ISSUE THREAD

**Issue by kafisatz** [JuliaDB/MySQL.jl#16]
Hi

I have a table with a BIGINT column in a MySQL database. the largest value is 4'871'095'025. This leads to an overflow error when reading the table into Julia.
I did  not (yet) find time to find out why exactly that happened. I guess it must be converted to Int32 somewhere. 

I am using a 64 Bit driver though. After all, I can write the data successfully to the SQL database using SAS. SAS is (to my knowledge) using the same driver as Julia.
Did you ever check a read of a BigInt >typemax(Int32)?

I will try and have a deeper look at this later today.

**Comment by nkottary** [comment]
It works fine for me. The problem I would guess is here. (line 32 src/results.jl)

```
    elseif (mysqltype == MYSQL_TYPE_LONGLONG)
        return Clong # change this to Int64
```

Can you try this? If it works send a pull request.

**Comment by kafisatz** [comment]
Thanks that nearly fixed it. See my PR. 
I do not know why C(u)long are 32 bit on my system though.... It seems they are 64 bit on yours.

**Comment by ViralBShah** [comment]
Clong is 32-bit on 32-bit systems and 64-bit on 64-bit systems. If you want to force a 32-bit C integer type, you should use Cint.

**Comment by kafisatz** [comment]
@ViralBShah 

Why is Clong 32 bit Int on my system? 
I have 64-bit Windows and Julia (see below).
Or is this 32-bit Julia?

I will close this as the merged PR resolves this issue.

julia> Clong
Int32

julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia>

**Comment by ViralBShah** [comment]
I think Windows is perhaps a bit different. @tkelman Any ideas? On my mac, Clong is Int64.

**Comment by tkelman** [comment]
On Win64 Clong is 32 bits, windows convention is LLP64.

**Comment by ViralBShah** [comment]
What? Why? Whatever.

**Comment by tkelman** [comment]
This is why we have the Ctype aliases, because they're system dependent. Sane libraries should be using C99 definitively-sized types like int64_t , but convincing existing libraries of that is not the simplest thing to do given the breakage it could cause to existing applications.
