### ISSUE TITLE
MySQL.jl is approximating Double and Double Precision types while retrieving 

### ISSUE THREAD

**Issue by bmharsha** [JuliaDB/MySQL.jl#21]
MySQL.jl is not returning the original value (As stored in Database) for columns of type ```Double and Double Precision``` instead it is approximating the value to 5 decimal places while retrieving , this bug can be reproduced using following steps 

```
mysql_execute_query(temp_conn, "CREATE TABLE Employee(z1 DOUBLE, z2 DOUBLE PRECISION);")
mysql_execute_query(temp_conn, "INSERT INTO Employee (z1,z2) values (0.26020991802215576,0.26020991802215576602099180221557);")
mysql_execute_query(temp_conn, "select * from Employee")
1x2 DataFrames.DataFrame
| Row | z1      | z2      |
|-----|---------|---------|
| 1   | 0.26021 | 0.26021 |
```

**Comment by nkottary** [comment]
This is not a bug. Dataframes are displayed with float/double values rounded off to 5 digits after the point.

If you access the values of the dataframe using indices (such as `df[1, :z1]`) you will see the complete values.
