### ISSUE TITLE
Problem parsing SQL Timestamps

### ISSUE THREAD

**Issue by matthewrfellows** [JuliaDB/MySQL.jl#26]
I'm querying a table containing two columns of type TIMESTAMP.

When running, e.g.,
```
con=mysql_connect(<host>,<user>,<password>,<database>)
mysql_execute_query(con, "select id, created_on, added_on from table")
```

I get the following error

ERROR: ArgumentError: invalid base 10 digit '-' in "2013-03-14 00:00:00"
 in tryparse_internal at parse.jl:92
 in tryparse_internal at parse.jl:136
 in parse at parse.jl:146
 in mysql_interpret_field at /folder/.julia/v0.4/MySQL/src/results.jl:98
 in populate_row! at /folder/.julia/v0.4/MySQL/src/results.jl:271
 in mysql_result_to_dataframe at /folder/.julia/v0.4/MySQL/src/results.jl:297
 in mysql_execute_query at /folder/.julia/v0.4/MySQL/src/handy.jl:110
 in mysql_execute_query at /folder/.julia/v0.4/MySQL/src/handy.jl:72

If I omit the two TIMESTAMP columns from the query, the results come back with no error.

**Comment by nkottary** [comment]
@matthewrfellows, would you like to try #28 and see if it fixes your issue before I merge it ?

**Comment by matthewrfellows** [comment]
Works great now. Thanks!
