### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION from mysql_stmt_execute with large inserts

### ISSUE THREAD

**Issue by amellnik** [JuliaDB/MySQL.jl#44]
I'm seeing a new access violation error when performing large insert statements using the prepared statement version of `mysql_execute`.  I haven't been able to localize the problem well -- inserting the same 10k rows works fine sometimes, but fails other times, and there's nothing that stands out about the rows near where the statement failed.  It seems possible that any individual row has a very small chance of failing as `mysql_execute` is called once per row.

I'm also not sure what's supposed to be happening when it fails since the function in the highest level error apparently [does nothing](https://dev.mysql.com/doc/refman/5.7/en/mysql-stmt-param-metadata.html).  

Any suggestions on the best way to look into this?  

```
Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffd5117a299 -- mysql_stmt_param_meta
data at  (unknown line)
mysql_stmt_param_metadata at C:\Program Files\MySQL\MySQL Connector.C 6.1\lib\li
bmysql.dll (unknown line)
mysql_stmt_param_metadata at C:\Program Files\MySQL\MySQL Connector.C 6.1\lib\li
bmysql.dll (unknown line)
mysql_stmt_param_metadata at C:\Program Files\MySQL\MySQL Connector.C 6.1\lib\li
bmysql.dll (unknown line)
mysql_stmt_execute at C:\Program Files\MySQL\MySQL Connector.C 6.1\lib\libmysql.
dll (unknown line)
mysql_stmt_execute at C:\Users\amellnik\.julia\v0.4\MySQL\src\handy.jl:240
mysql_execute at C:\Users\amellnik\.julia\v0.4\MySQL\src\handy.jl:190
jlcall___mysql_execute#19___2926 at  (unknown line)
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.4.5\bin\libjulia.dll
 (unknown line)
julia_mysql_execute_2925 at  (unknown line)
executeReplaceStatement at C:\Users\amellnik\Documents\Julia libraries\XXXX\src\XXXXX.jl:39
jlcall_XXXXXX_2892 at  (unknown line)
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.4.5\bin\libjulia.dll
 (unknown line)
jl_interpret_toplevel_expr at C:\Users\amellnik\AppData\Local\Julia-0.4.5\bin\li
bjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\amellnik\AppData\Local\Julia-0.4.5\
bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\amellnik\AppData\Local\Julia-0.4.5\bin\libju
lia.dll (unknown line)
jl_parse_eval_all at C:\Users\amellnik\AppData\Local\Julia-0.4.5\bin\libjulia.dl
l (unknown line)
jl_load_file_string at C:\Users\amellnik\AppData\Local\Julia-0.4.5\bin\libjulia.
dll (unknown line)
include_string at loading.jl:282
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.4.5\bin\libjulia.dll
 (unknown line)
execute_request_0x535c5df2 at C:\Users\amellnik\.julia\v0.4\IJulia\src\execute_r
equest.jl:182
jlcall_execute_request_0x535c5df2_1580 at  (unknown line)
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.4.5\bin\libjulia.dll
 (unknown line)
eventloop at C:\Users\amellnik\.julia\v0.4\IJulia\src\IJulia.jl:142
jl_apply_generic at C:\Users\amellnik\AppData\Local\Julia-0.4.5\bin\libjulia.dll
 (unknown line)
anonymous at task.jl:447
jl_unprotect_stack at C:\Users\amellnik\AppData\Local\Julia-0.4.5\bin\libjulia.d
ll (unknown line)
```

**Comment by amellnik** [comment]
I think I found a way to avoid the problem, if not a solution or root cause.  I realized I had a much larger insert statement which always worked.  One difference was that in this working table, all the columns which were being mapped to ```varchar``` in MySQL were of type ```UTF8String```, whereas in in the failing table I had a mix of ```UTF8String``` and ```ASCIIString```.  (```mysql_execute``` returns strings as ```AbstractString``` or ```ASCIIString``` [here](https://github.com/JuliaDB/MySQL.jl/blob/f0e3a67aa588ed22b132e870afc5d4443802bb1f/src/results.jl#L67)).  I started converting everything over to ```UTF8String``` and haven't seen the problem since.

Can anyone think of any reason why using ```ASCIIString``` would cause prepared insert statements to fail randomly some <0.1% of the time?  Is there a reason why string results are returned as ```AbstractString```?

**Comment by amellnik** [comment]
I have a working theory, and a workaround that has so far inserted a few 100k rows without failure:   this appears to be related to garbage collection.

I noticed that right before the process died the total memory used by the process dropped by a few hundred MB.  I started manually calling ```gc()``` before every 1000th ```mysql_execute``` and now the memory usage stays constant and about 700 MB lower than where the the process was failing previously.  I know nothing about how how julia's garbage collector works, but my wild guess is that some c struct is not correctly being marked as "in use" and gets freed, then libmysql.dll is handed a pointer to the no-longer-existing object.  

I'll start reading up on how the gc works and see if anyone with more familiarity of how it works can take a look.

**Comment by amellnik** [comment]
@yuyichao, @carnaval, @timholy and/or @tkelman: This is a long shot, but I think an issue I'm seeing with MySQL.jl is actually due to the gc chomping on objects that are still in use.  If any of you can tell if this is an issue with the module or the gc itself that would be a big help.

**Comment by nkottary** [comment]
@amellnik, it could be a bug in MySQL 6.1 could you try an earlier version like 5.7 ?

**Comment by yuyichao** [comment]
The use of `ccall` is unsafe in many places but I don't think julia 0.4 is doing any of the optimization yet...

**Comment by yuyichao** [comment]
And if it is not a mysql bug, a script to reproduce the issue (to at least show what you are doing) and what do you think is corrupted would be better. You can also compile julia with `MEMDEBUG` (`options.h`) or `WITH_GC_DEBUG_ENV=1` (`make` variable) to catch memory error.

**Comment by amellnik** [comment]
@yuyichao I haven't been able to make a standalone script that reproduces the error.  My best attempt looks like:

```julia
using MySQL, DataFrames
conn = mysql_connect("127.0.0.1", "root", "", "test")
@time data = DataFrame(
    c1 = UTF8String[randstring(255) for i in 1:100000]
    ,c2 = UTF8String[randstring(10000) for i in 1:100000]
    ,c3 = UTF8String[randstring(10000) for i in 1:100000]
    );
mysql_stmt_prepare(conn, "REPLACE INTO test (c1, c2, c3) values (?, ?, ?);")
function insertRows(df)
    for (r,i) in zip(eachrow(df), 1:nrow(df))
        mod(i,100)==0 ? print(i, " ") : nothing
        mysql_execute(conn, [MYSQL_TYPE_VARCHAR, MYSQL_TYPE_VARCHAR, MYSQL_TYPE_VARCHAR],
        tuple([r[c] for c in names(r)]...))
    end
end
insertRows(data)
```

This mirrors my code as close as I can get it, but i haven't yet observed a crash with it.  I'm running the code continuously to see if it dies at some point.  

@nkottary This is with MySQL 5.7 and version 6.1 of the c connector.  The oldest version I see of the c connector is 6.0, which I will try later in the day.

**Comment by yuyichao** [comment]
@amellnik A few things you can try to figure out if the GC is freeing the memory too eagerly,

1. disable GC

2. put a `print` in the finalizer to see if it is called (this cannot be the julia point function but you can `ccall` `printf` or `jl_`, e.g. `ccall(:printf, Cint, (Ptr{UInt},), ".....")` or `ccall(:jl_, Void, (Any), "....")`)

3. If you have a debugger, try to check what is the invalid address and how it got it.

A brief summary of incorrect use of `ccall`:

1. Bottom line, no functions in `api.jl` should take a pointer as an argument.

2. `mysqlptr`, `stmtptr`, `bind`

    These should use custom `unsafe_convert`, `cconvert`. Ref https://github.com/ihnorton/Clang.jl/issues/152 https://github.com/JuliaGPU/VulkanCore.jl/pull/1#discussion_r53778385 and the manual section about calling C functions

3. `unix_socket`

    This should just be a string. It seems that `NULL` is allowed so in that case you can pass in `C_NULL`, otherwise, always pass in the julia object and **do not** convert to  pointer manually.

4. `option`

    Pass in the string or array directly.

**Comment by amellnik** [comment]
@yuyichao This is an excellent list and I'll start going through these items as best I can.  Thanks!

**Comment by amellnik** [comment]
Closing -- not seen on 0.5+
