### ISSUE TITLE
MethodError: `convert` has no method matching convert(::Type{BitArray{N}}, ::Int64)

### ISSUE THREAD

**Issue by xqrongm** [JuliaDB/MySQL.jl#47]
The same version of Julia and MySQL work just fine on my 64-bit PC, except that when I installed it a while ago (can't say for sure it's still a problem now), I had to change "libmysql.dll" in "config.jl" to the full path to the .dll, even though the directory is already in the system PATH.

Anyway, the problem happens on arm-linux-gnueabihf, 32 bit

julia> VERSION
v"0.4.5"

julia> Pkg.status()
...
- MySQL                         0.0.2
  ...

julia> mysql_execute(db_conn_, "select \* from just2test")
ERROR: MethodError: `convert` has no method matching convert(::Type{BitArray{N}}, ::Int64)
This may have arisen from a call to the constructor BitArray{N}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T,N}(::Type{BitArray{N}}, ::AbstractArray{T,N})
  convert{T}(::Type{T}, ::T)
  ...

julia> Pkg.test("MySQL")
INFO: Testing MySQL

**\* Running Basic Test ***

SUCCESS: Create database
SUCCESS: Create user
SUCCESS: Grant privilege
SUCCESS: Create table
SUCCESS: Insert
Last insert id was 1
SUCCESS: Update
SUCCESS: Insert Null row
ERROR: LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{BitArray{N}}, ::Int64)
This may have arisen from a call to the constructor BitArray{N}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T,N}(::Type{BitArray{N}}, ::AbstractArray{T,N})
  convert{T}(::Type{T}, ::T)
  ...
while loading /root/.julia/v0.4/MySQL/test/test_basic.jl, in expression starting on line 109
while loading /root/.julia/v0.4/MySQL/test/runtests.jl, in expression starting on line 8
================================[ ERROR: MySQL ]================================

failed process: Process(`/sdcard/upgrade/julia-0.4.5/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /root/.julia/v0.4/MySQL/test/runtests.jl`, ProcessExited(1)) [1]
# 

ERROR: MySQL had test errors

**Comment by quinnj** [comment]
shouldn't be an issue anymore
