### ISSUE TITLE
Decimal value incorrect using prepared statements

### ISSUE THREAD

**Issue by kevmal** [JuliaDB/MySQL.jl#52]
Seems specifically decimal fields (Int,Date,DateTime come through fine) are read incorrectly using mysql_execute with a prepared statement. For example:

```
conn = mysql_connect("host", "user", "password", "db")
statement = "SELECT 9.0"
mysql_stmt_prepare(conn, statement)
bleh = mysql_execute(conn)
bleh2 = mysql_execute(conn,statement)
```

Im seeing

```
julia> bleh
1×1 DataFrames.DataFrame
│ Row │ 9.0          │
├─────┼──────────────┤
│ 1   │ 2.41909e-312 │

julia> bleh2
1×1 DataFrames.DataFrame
│ Row │ 9.0 │
├─────┼─────┤
│ 1   │ 9.0 │


```

**Comment by nkottary** [comment]
This issue occurs because we don't have support for `BigFloat` type yet.  This means using type `DECIMAL` will not work with prepared statements.  Types `FLOAT` and `DOUBLE` work properly.

**Comment by ViralBShah** [comment]
What does this have to do with `BigFloat`?

cc @simonbyrne

**Comment by nkottary** [comment]
When we execute `SELECT 9.0;` the value is returned as the `DECIMAL` type.  This is MySQL's arbitrary precision type.  The binary format for this is explained [here](https://github.com/twitter/mysql/blob/master/strings/decimal.c) (Search for decimal2bin).

**Comment by ViralBShah** [comment]
Does MySQL's arbitrary precision type roughly map on to our BigFloat?

**Comment by simonbyrne** [comment]
BigFloat is still base-2, so can't represent decimal values exactly.

**Comment by nkottary** [comment]
The workaround for this would be to use `FLOAT` and `DOUBLE` types instead of `DECIMAL`.  To make `DECIMAL` work on prepared statement we would need to implement the `decimal2bin` c function in julia as it is not exposed in the `libmysqlclient.so` file.

**Comment by quinnj** [comment]
301a3458432f09b4289c82df38c1408b94747188 added proper support for Decimal types through use of the DecFP.jl package.
