### ISSUE TITLE
Warning about method def overwrite for MySQLResult only in v 0.6

### ISSUE THREAD

**Issue by colbec** [JuliaDB/MySQL.jl#55]
Using 

```
Julia Version 0.6.0-dev.67
Commit 9c21452* (2016-08-07 07:03 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

I see a warning in version 0.6 but not in 0.4 (0.5 unknown). Results seem to be fine, so perhaps it is just cosmetic.
Here is the warning:
`WARNING: Method definition (::Type{MySQL.MySQLResult})(Any, Any) in module MySQL at /home/colin/.julia/v0.6/MySQL/src/types.jl:157 overwritten at /home/colin/.julia/v0.6/MySQL/src/handy.jl:313.`

**Comment by nkottary** [comment]
Fixed by #71
