### ISSUE TITLE
Fails on PackageEval

### ISSUE THREAD

**Issue by ranjanan** [JuliaDB/MySQL.jl#57]
This fails on v0.4 and v0.5 on PackageEval. The logs can be found here: http://pkg.julialang.org/detail/MySQL.html.

**Comment by aviks** [comment]
Probably needs mysql-client installed in the vagrant box? cc: @tkelman

**Comment by tkelman** [comment]
Would be more general to have the package check and install it if it's not yet present.

**Comment by ranjanan** [comment]
Yeah, I think mariadb is one of the preinstalled packages on ubuntu, which is why Travis CI works for this package. I think we probably need to modify the PackageEval script according to what is specified [here](https://github.com/JuliaDB/MySQL.jl/blob/master/.travis.yml#L7)

**Comment by tkelman** [comment]
That would only handle installation on PackageEval. If you fix it in the package with a build.jl BinDeps script, you fix the installation issue for everyone who uses the package.
