### ISSUE TITLE
Is it possible for MySQL package to use `__precompile__()`?

### ISSUE THREAD

**Issue by xqrongm** [JuliaDB/MySQL.jl#58]
Sorry this isn't exactly an issue. I'm trying to write a module that depends on MySQL.jl. It'll be nice if I can use `__precompile__()` on my module, but I can't because MySQL.jl doesn't use `__precompile__()`. I just wonder if it is possible for MySQL package to use `__precompile__()`. If not, why? Thanks.

**Comment by nkottary** [comment]
Ref: #59
