### ISSUE TITLE
"InitError: Method called with null connection" when precompiling

### ISSUE THREAD

**Issue by xqrongm** [JuliaDB/MySQL.jl#60]
Julia v0.4.6
MySQL 0.0.2+ master

Thanks a lot for adding `__precompile__()`. I cloned the latest master with `__precompile__()` and wrote this module:
```
__precompile__()
module test_mysql
    using MySQL
    db_conn = mysql_connect("localhost", "user", "password", "test_1ch")
    ms_df1 = mysql_execute(db_conn, "select * from steps where id=2")
    function __init__()
        global ms_df2 = mysql_execute(db_conn, "select * from steps where id=2")
    end
end # test_mysql
```
Then
`using test_mysql`

This is the output:
> INFO: Precompiling module MySQL...
> INFO: Precompiling module test_mysql...
> ERROR: InitError: Method called with null connection.
>  in mysql_execute at E:\for_programs\julia_pkgs\v0.4\MySQL\src\handy.jl:144
>  in __init__ at E:\freelance\applications\010_qpcr\Julia\test_mysql.jl:7
>  in _require_from_serialized at loading.jl:84
>  in _require_from_serialized at loading.jl:109
>  in require at loading.jl:235
> during initialization of module test_mysql

It looks like the `db_conn` in `ms_df1 = mysql_execute(db_conn, "select * from steps where id=2")` was a valid connection (because no error was raised before `__init__` was called), while the `db_conn_` in `global ms_df2 = mysql_execute(db_conn, "select * from steps where id=2")` becomes a null connection for some reason I don't understand.

When I remove the `__precompile__()` before `module test_mysql` and `using test_mysql`, no error was raised and both `ms_df1` and `ms_df2` have valid values as expected, which means `db_conn` was a valid connection when used by both `ms_df1` and `ms_df2`.

**Comment by nkottary** [comment]
That is how precompilation works.  The reason you did not see the error on removing `__precompile__()` is because julia recompiled the file as it was changed.  If you run it again you will see the error.  You need to put the connection statement in `__init__`.

**Comment by xqrongm** [comment]
I don't quite understand why is the connection defined outside of `__init__` can be recognized in `__init__` without precompiling but cannot be recognized during precompiling.

**Comment by xqrongm** [comment]
I changed my code to this:
```
__precompile__()
module test_mysql
    using MySQL
    i1 = 1
    db_conn = mysql_connect("localhost", "root1", "pswd1", "test_1ch")
    ms_df1 = mysql_execute(db_conn, "select * from steps where id=2")
    function __init__()
        global i2 = i1 + 1
        global ms_df2 = mysql_execute(db_conn, "select * from steps where id=2")
    end
end # test_mysql
```
After `using test_mysql` and REPL attempt to precompile `test_mysql`, `i2` becomes 2 as expected, `ms_df2` was undefined probably because `db_conn` was recognized as a null connection. Since `db_conn` was not undefined, it must have been defined as a valid connection and somehow changed to a null connection before used by the `ms_df2 = ` statement. I would like to find out why was it changed. Thanks.

**Comment by nkottary** [comment]
I called dump on the connection and it gave:
```
MySQL.MySQLHandle 
  mysqlptr: Ptr{Void} Ptr{Void} @0x0000000000000000
  host: ASCIIString "127.0.0.1"
  user: ASCIIString "root"
  db: ASCIIString ""
  stmtptr: Ptr{MySQL.MYSQL_STMT} Ptr{MySQL.MYSQL_STMT} @0x0000000000000000
dump(conn) = nothing
```

Notice that the pointers are null (i.e 0, if you dump the connection in the repl they wont be null).  The reason is that pointers are specific to the process.  Constants (like 1) are not.  Therefore pointers are set to 0 on precompile.  Thats my guess.
