### ISSUE TITLE
LoadError: MYSQL library not found

### ISSUE THREAD

**Issue by zhangliye** [JuliaDB/MySQL.jl#64]
using MySQL

![image](https://cloud.githubusercontent.com/assets/8065051/18607772/32fa8f66-7d09-11e6-9cd9-18b0f9467879.png)

**Comment by zhangliye** [comment]
It is solved by putting the directory of "libmysql.dll" to the ENV variable of "PATH".

**Comment by zhangliye** [comment]
I just test the latest code using
Pkg.checkout("MySQL")

The speed is fast.

**Comment by ViralBShah** [comment]
Seems like the issue can be closed.

**Comment by amellnik** [comment]
This was mentioned in the README at one point, but was removed in a recent update.  It might be good to add this back in as pretty much every Windows user will need to do this.
