### ISSUE TITLE
API Questions

### ISSUE THREAD

**Issue by aviks** [JuliaDB/MySQL.jl#7]
`obtainResultsAsDataFrame` seems like a very awkward name.  

DataFrames has a `readtable` function that reads csv files and produces dataframes. I have added an additional `readtable` method in JDBC.jl, which takes in a JDBC `Results` object, and produces a dataframe. That would have been a nice API, but here everything is a `Ptr` rather than a typed object. 

So I don't have a good solution, just to say that `obtainResultsAsDataFrame` sounds like something from a bad Java library!

In between the raw pointers and DataFrames, it may be useful to have a an iterator over the rows of a result, and the ability to get the fields from the rows as primitive values (ints, floats, strings). Basically expose some of the code that is used to populate the dataframe. 

With that, Dataframes might become an optional dependency (via Require.jl) wherein the `obtainResultsAsDataFrame` method is defined only when Dataframes is loaded.

**Comment by nkottary** [comment]
I have added functions to convert mysql results from raw pointers to julia arrays. A brief description of the API's :-

1) mysql_get_field_metadata(), mysql_get_field_types() -- Get an array of field metadata or just types respectively.

2) mysql_get_row_as_vector(), mysql_get_result_as_array() -- Get a row or the entire result as an array.

3) MySQLRowIterator -- Iterate through rows like this :-
```
mysql_query(conn, "SELECT * FROM some_table;")
result = mysql_store_result(conn)

for row in MySQLRowIterator(result)
    do_something_with(row)
end
```

There are some examples in the readme.

**Comment by quinnj** [comment]
MySQL.jl now support DataStreams, which gives automatic interoperability w/ all other packages that also implement the interface (e.g. CSV.jl, Feather.jl, SQLite.jl, ODBC.jl, etc.). MySQL query resultsets can also be iterated over via `Data.rows(query)`, also provided automatically by DataStreams.
