### ISSUE TITLE
Performance with bulk inserts

### ISSUE THREAD

**Issue by amellnik** [JuliaDB/MySQL.jl#70]
I'm inserting rows using roughly the method outlined in the docs:

``` julia
mysql_stmt_prepare(conn, "INSERT INTO Employee (Name, Salary, JoinDate) values (?, ?, ?);")

values = [("John", 10000.50, "2015-8-3"),
          ("Tom", 20000.25, "2015-8-4"),
          ("Jim", 30000.00, "2015-6-2")]

for val in values
    mysql_execute(conn, [MYSQL_TYPE_VARCHAR, MYSQL_TYPE_FLOAT, MYSQL_TYPE_DATE], val)
end
```

However, the performance is poor.  Inserting 9k rows with four columns takes about 16 seconds for me.  Is there any suggested method for speeding this up, or does anyone happen to know what's limiting the performance here?

**Comment by nkottary** [comment]
You can try executing multiple `INSERT` commands in one statement.  However, you cannot use prepared statements then since only statements with a single command can be prepared.

**Comment by quinnj** [comment]
Bulk inserts should be faster now, and there's probably even more room for improvement. The new API to bulk insert is like:

```julia
source = ... # any Data.Source: 
stmt = MySQL.Stmt(conn, "insert into Employee (Name, Salary, JoinDate) values (?, ?, ?);")
Data.stream!(source, stmt)
```
