### ISSUE TITLE
MySQL LOAD DATA LOCAL INFILE

### ISSUE THREAD

**Issue by ningHub** [JuliaDB/MySQL.jl#75]
I am using MySql 5.5.53-0ubuntu0.14.04.1, and Julia Version 0.5.0
In my julia script, I am using
conn = MySQL.mysql_connect(host, username, password, database)
command = string("LOAD DATA LOCAL INFILE 'infile' INTO TABLE temp_table FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"';")
MySQL.mysql_execute(conn, command) 
I got the error message “The used command is not allowed with this MySQL version”

The command does work when I was running it directly on the MySQL console, so I am assuming it is an issue with Julia MySQL.mysql_connect .

Looks like there is a similar problem with Python, and the following syntax solves the problem. 
MySQLdb.connect(server, username, password, database, local_infile = 1)

I wonder how should I do this with Julia?

**Comment by nkottary** [comment]
The equivalent in julia would be `mysql_connect(host, user, passwd, db, opts=Dict(MYSQL_OPT_LOCAL_INFILE => 1))`

**Comment by ViralBShah** [comment]
Close?

**Comment by ningHub** [comment]
nkottary<https://github.com/nkottary>:

Thank you very much!!

It works for me.


Is this in any of the Julia document?


Ning

________________________________

**Comment by nkottary** [comment]
You can find documentation on various options [here](http://dev.mysql.com/doc/refman/5.7/en/mysql-options.html).

**Comment by ningHub** [comment]
Thanks!


Sent from my Galaxy S®III


-------- Original message --------
From: "Nishanth H. Kottary"
Date:12/08/2016 10:22 PM (GMT-07:00)
To: "JuliaDB/MySQL.jl"
Cc: ningHub , Author
Subject: Re: [JuliaDB/MySQL.jl] MySQL LOAD DATA LOCAL INFILE (#75)


You can find documentation on various options here<http://dev.mysql.com/doc/refman/5.7/en/mysql-options.html>.

-
