### ISSUE TITLE
Precompile fails on new 0.6 alpha

### ISSUE THREAD

**Issue by xximranxx** [JuliaDB/MySQL.jl#77]
`VERSION`

> v"0.6.0-pre.alpha.0"

`using MySQL`

> LoadError: Failed to precompile MySQL to

Just fyi, see this to regarding 0.6 release
https://discourse.julialang.org/t/julia-0-6-alpha-released-please-update-your-projects/2571

**Comment by quinnj** [comment]
no longer an issue
