### ISSUE TITLE
Use DataStreams.jl

### ISSUE THREAD

**Issue by mirestrepo** [JuliaDB/MySQL.jl#78]
I'm wondering if it would be a good idea to have MySQL.jl use Sink/Source from DataStreams.... one of the advantages would be the ability to be compatible with the generic interface of Query.jl. What is your view on it? Maybe @quinnj could comment on the advantages and requirements of such model, since that's what SQLite.jl uses.

If this is an effort that makes sense, I'd be happy to contribute.

**Comment by quinnj** [comment]
I think it should be pretty straightforward.

**Comment by quinnj** [comment]
301a3458432f09b4289c82df38c1408b94747188 added proper DataStreams.jl support.
