### ISSUE TITLE
LoadError: MYSQL library not found under Mac OS X

### ISSUE THREAD

**Issue by scls19fr** [JuliaDB/MySQL.jl#80]
Hello,

I installed MySQL community
https://dev.mysql.com/downloads/mysql/
for Mac OS X (10.12.4)

MySQL server works correctly (I tested it using MySQL Workbench) but I haven't been able to connect to this server using Julia.

```julia
julia> using MySQL
INFO: Precompiling module MySQL.
ERROR: LoadError: LoadError: MYSQL library not found
```

https://github.com/JuliaDB/MySQL.jl#how-to-solve-mysql-library-not-found-error
didn't help me much

Any idea?

Kind regards

**Comment by apurvis** [comment]
I have a similar issue on OS X but with
* El Capitan 
* a `homebrew` installation of mysql (*actually percona server version 5.6* - this might be problem)

There is simply no library called `libmysqlclient.dylib` when i `find / -iname`.

There *is* a lib called `libperconaserverclient.dylib`.  Is that what I need?

If it is, then from the docs:

> Just add the MariaDB/MySQL .so file to lib_choices array in src/config.jl

Very new to Julia so I don't know what/where `src/config.jl` is or how to try this out.  @nkottary can you give some hints?  I'll update the `README` if we can sort this out.

**Comment by czechkate1** [comment]
Same issue, MacOS Sierra 10.12.4
ERROR: LoadError: LoadError: MYSQL library not found
Has anyone been able to resolve this?

**Comment by rui-mesquita** [comment]
@czechkate1: I changed the `config.jl` file in `/Applications/JuliaPro-0.5.2.1.app/Contents/Resources/pkgs-0.5.2.1/v0.5/MySQL/src` to include the dylib file in `/usr/local/lib/tdbcmysql1.0.4`, in the row that covers the Apple OS.

Hope that helps. Although I have found an error for _could not find function for mysql_init_

I am using JuliaPro and MySQLWorkbench installed from GUI.

**Comment by czechkate1** [comment]
It does help @rui-mesquita, thanks. Getting the same mysql_init error when I run Pkg.test(). Also tried the mariadb dylib file as recommended here: 

[https://github.com/JuliaDB/MySQL.jl#how-to-solve-mysql-library-not-found-error](url)

but get access denied error.

ERROR: LoadError: LoadError: Access denied for user 'root'@'localhost' (using password: NO)

**Comment by nkottary** [comment]
See [this](https://stackoverflow.com/questions/1857861/libmysqlclient15-dev-on-macs) Stackoverflow thread.

You would need to run:

```
brew install mysql
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH
```

In order to run the tests you need to have a mysql server running somewhere. See the file `test/server.ini` for what credentials are used to login to the server. You can edit this accordingly.

**Comment by rahulkp220** [comment]
@nkottary Yes! thats helpful.
