### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by staticfloat** [JuliaDB/MySQL.jl#83]
It'd be great to get a new release of this sometime soon in preparation for 0.6

**Comment by amellnik** [comment]
More frequent releases would be appreciated.  We're on master since there hasn't been a tagged release since last year, but things like https://github.com/JuliaDB/MySQL.jl/pull/86 break pretty much everything downstream.

**Comment by aviks** [comment]
I've proposed a v0.2.0 release on the commit before #86 

https://github.com/JuliaLang/METADATA.jl/pull/10826

**Comment by aviks** [comment]
This has now been merged. cc: @nkottary
