### ISSUE TITLE
MySQL.mysql_execute is highly type instable

### ISSUE THREAD

**Issue by essenciary** [JuliaDB/MySQL.jl#84]
According to the README, it should return 2 types, a `DataFrame` or a `Tuple`, depending on `opformat`. But that is not the case. By trial and (assertion) error I figured out that there are at least 4 high-level types being returned: `DataFrame` and `Tuple` but also `Int` (for the number of rows affected) and `Vector{DataFrame}`. 

The `Tuple` itself is an extra source of type instability, as each `Tuple` has the type determined by the types and number of its elements. So depending on what and how many columns are queried and returned, the type of the `Tuple` will change. 

A low-level library like this should have performance and predictability at its core. In my opinion, at least it should _always_ return one of the two types, as instructed by `optformat` (thus still being type unstable, but predictable). So it should always return either a `Tuple` or a `Vector{DataFrame}`. Instead of the current `DataFrame` it should be a `Vector{DataFrame}` of one item. And it should also wrap the `Int` in a `DataFrame`. This way, by always using the `MYSQL_DATA_FRAME` `optformat` the function would stay type stable.

**Comment by essenciary** [comment]
More on the subject of types, it looks like a query like this will return `Nullables`: 
```
SELECT
      CAST(SUM(polarity = -1) AS SIGNED) AS negative,
      CAST(SUM(polarity = 0) AS SIGNED) AS neutral,
      CAST(SUM(polarity = 1) AS SIGNED) AS positive,
      CAST(SUM(subjective = TRUE) AS SIGNED) AS subjective,
      CAST(SUM(subjective = FALSE) AS SIGNED) AS objective
    FROM tweets
``` 
Not a bad idea, but it would help to know what to expect. So maybe a section on return types could be quite useful.

**Comment by mirestrepo** [comment]
Is there a plan to tag a new release soon that includes this changes?

**Comment by quinnj** [comment]
In 301a3458432f09b4289c82df38c1408b94747188, the querying interface was overhauled to leverage DataStreams.jl. I.e. the new way to query is `MySQL.query(conn, sql, sink)`, where `conn` is a valid MySQL connection, `sql` is the SQL statement to execute, and `sink` is a valid DataStreams `Data.Sink` (e.g. `DataFrame`, `Data.Table`, `Data.RowTable`, `CSV.Sink`, `Feather.Sink`, etc.). By default, queries are streamed to `Data.Table`, which is really just an alias for a NamedTuple of Vectors. A resultset's rows can also just be iterated by creating Query object directly `MySQL.Query(conn, sql)`, and then using the DataStreams interface for iterating sources, `Data.rows(query)`.

This means return types for querying are now much more predictable.

**Comment by essenciary** [comment]
😍 👏
